---
title: "Notas"
output: bookdown::html_notebook2
editor_options: 
  chunk_output_type: console
---

# Pacotes usados

```{r, message=FALSE}
library(readr)
library(readxl)
library(openxlsx)
library(tidyverse)
```

# Descrição do projeto

**Título:** Infância em tempos de Pandemia: Experiências de crianças 8 a 12 anos durante o isolamento social em diferentes contextos.

Consulente: Juliana Prates Santana e Adriana Freire Pereira Ferriz.

# Pesquisa de referência

**Título da pesquisa:** Infâncias em tempos de Pandemia; experiências das crianças da grande BH
**Pùlbico alvo:** Criança de 8 a 12 que tiveram a rotina alterada devido a pandemia de COVID-19
**Objetivo:** O objetivo geral foi o de compreender como essas crianças vivenciam a pandemia de COVID-19

Os resultados apresentados foram:

* Gráfico de barras da variável município de residência
* Gráfico espacial da distribuição das crianças (?)
* Gráfico da tipologia da residência (favela, condomínio...)
* Vulnerabilidade territorial do local de moradia
* Gráfico (de barras) da Composição dos moradores da casa
* Gráfico (de barras) das idades das crianças
* Gráfico de barras da raça
* Gráfico de barras de gênero
* Gráfico de barras de tipo de escola
* Associação entre _vulnerabilidade territorial_ e _tipo de escola_
* Associação entre _acesso a internet_ e _raça_
* Associação entre _vulnerabilidade territorial_ e _TIC_
* Respeito ao isolamento social
* Associação entre _preocupação com falta de comida_ e _raça_
* Relação com a família durante a pandemia
* Agregar várias respostas de acordo com sim ou não (atividades durante a pandemia)
* Associação entre _participação em atividades domésticas_ e _gênero_
* Agrupamento de respostas: Escola e as crianças

